myproject/webapp/urls.py
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from sitemap import ProductSitemap, CategorySitemap, ViewSitemap

from . import views

sitemaps = {
	'product': ProductSitemap,
	'category': CategorySitemap,
	'static': ViewSitemap,
}

app_name = 'webapp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^policy/$', views.policy, name='policy'),
    url(r'^disclaimer/$', views.disclaimer, name='disclaimer'),
    url(r'^category/$', views.category, name='category'),
    url(r'^category/(?P<cat_id>[0-9]+)/$', views.category_view, name='category_view'),
    url(r'^product/(?P<product_id>[0-9]+)/$', 
    	views.product, name='product'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

myproject/webapp/models.py
from __future__ import unicode_literals

from django.db import models
from uuid import uuid4

# Create your models here.
def post_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid4().hex, ext)

    product_name = instance.product_id.name.replace(" ", "_")
    product_name = product_name.replace("/", "")

    return 'webapp/images/product_{0}/{1}'.format(product_name, filename)


class Category(models.Model):
    '''
    Catogory Model
    ManyToMany relationship with Product
    cat_id - index of the Catogory
    name - name of the Catogory
    '''
    cat_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return "/category/%i/" % self.cat_id


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    item_number = models.CharField(max_length=100, default="0000")
    name = models.CharField(max_length=200)
    categories = models.ManyToManyField(Category, related_name='categories')
    description = models.TextField()
    quantity = models.IntegerField()
    price = models.CharField(max_length=100, default="Request for Quote")
    sold = models.BooleanField(default=False)

    def __str__(self):
        return "%s %s" % (self.item_number, self.name)

    def get_absolute_url(self):
        return "/product/%i/" % self.product_id




class Picture(models.Model):
    '''
    Picture Model
    ManyToOne relationship with Product
    '''
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to=post_directory_path, blank=False, null=True)


class Webinfo(models.Model):
    '''
    Webinfo
    Information of Web
    '''
    home_description = models.TextField()
    terms_content = models.TextField()
    privacy_content = models.TextField()
    disclaimer_content = models.TextField()

    class Meta:
        verbose_name_plural = "Webinfo"

myproject/webapp/forms.py
from django import forms

class MailForm(forms.Form):

	item = forms.CharField(
		label="Item of Interest",
		widget=forms.TextInput(attrs={ 'required': 'true', 'placeholder': 'Product ID & Name*' })
		)

	name = forms.CharField(
		label="First Name", 
		max_length=100, 
		required=True,
		widget=forms.TextInput(attrs={ 'required': 'true', 'placeholder': 'Your Name*'})
		)

	email = forms.EmailField(
		label="Email",
		widget=forms.TextInput(attrs={ 'required': 'true', 'placeholder': 'Email*' })
		)

	phone = forms.CharField(
		label="Phone Number", 
		max_length=100, 
		widget=forms.TextInput(attrs={ 'required': 'true', 'placeholder': 'Phone Number*' })
		)


	message = forms.CharField(
		widget=forms.Textarea(attrs={ 'required': 'true', 'placeholder': 'Your Message*' }), 
		label="Message"
		)

	location = forms.CharField(
		label="Project Location", 
		widget=forms.TextInput(attrs={'placeholder': 'Location' })
		)

myproject/webapp/views.py
from webapp.util.page_util import *

from django.conf import settings
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from webapp.settings import *
from webapp.util.util import *
from .forms import MailForm
from urllib import urlencode
from webapp.models import Webinfo
from django.contrib.sitemaps import Sitemap



# Create your views here.

def index(request):
	"""
	Home page of the web app
	"""

	home_info = Webinfo.objects.all()[0]

	#Header
	#Package context
	context = {
		'current':'home',
		'title':'New Products On Sale',
		'category_list':getCategories(),
		'home_description': home_info,
	}



	return render(request, 'webapp/index.html', context)


def terms(request):
	"""
	Home page of the web app
	"""

	content = Webinfo.objects.all()[0].terms_content

	#Header
	#Package context
	context = {
		'current':'home',
		'title':'New Products On Sale',
		'category_list':getCategories(),
		'content': content,
	}



	return render(request, 'webapp/generic.html', context)


def policy(request):
	"""
	Home page of the web app
	"""

	content = Webinfo.objects.all()[0].privacy_content

	#Header
	#Package context
	context = {
		'current':'home',
		'title':'New Products On Sale',
		'category_list':getCategories(),
		'content': content,
	}



	return render(request, 'webapp/generic.html', context)


def disclaimer(request):
	"""
	Home page of the web app
	"""

	content = Webinfo.objects.all()[0].disclaimer_content

	#Header
	#Package context
	context = {
		'current':'home',
		'title':'New Products On Sale',
		'category_list':getCategories(),
		'content': content,
	}



	return render(request, 'webapp/generic.html', context)

def contact(request):
	"""
	Contact page of the web app
	"""

	context = {
		'current':'contact',
		'title':'Contact Us',
		'category_list':getCategories(),
	}

	# If POST request
	if request.method == 'POST':

		form = MailForm(data=request.POST)

		if form.is_valid():

			#Email the posted information to SMTP
			name = form.cleaned_data['name']
			phone = form.cleaned_data['phone']
			email = form.cleaned_data['email']
			item = form.cleaned_data['item']
			message = form.cleaned_data['message']
			location = form.cleaned_data['location']

			#Package data then email the message to smtp email
			try:
				subject = "Request for information of item %s" % item
				send_message = "Name: %s\nPhone number: %s\nItem: %s\nLocation: %s \nEmail: %s\n\nMessage: %s\n" % (name, phone, item, location, email, message)
				send_mail(subject, send_message, email, [settings.EMAIL_FORWARD])
			
			except BadHeaderError:
				return render(request, 'webapp/error.html', context)

			return render(request, 'webapp/thanks.html', context)
		else:
			return render(request, 'webapp/error.html', context)
	
	# If GET request
	else:
		item = request.GET.get("item", "")
		item = item.replace("_", " ")
		form = MailForm(initial={'item': item})

	context['form'] = form 


	return render(request, 'webapp/contact.html', context)


def category(request):
	"""
	Category page of the web app
	"""

	return redirect( reverse('webapp:category_view', 
		kwargs={'cat_id':0} )) 


def category_view(request, cat_id):
	"""
	Category page of the web app

	Keyword arguments:
	cat_name -- the name of the category
	cat_id -- the category if of the category
	"""

	#helper variables
	cat_id_int = int(cat_id)
	name = "All Products"
	page_num_int = 1
	search_url = ''
	searchpath = ''
	post_list = None
	post_info = None
	check_sold = Q(sold=False)

	#check GET request

	if 'page' in request.GET and request.GET['page'] != '':
		page_num_int = int(request.GET['page'])
		print page_num_int

	if 'search' in request.GET and request.GET['search'] != '':

		name = 'Search'
		search_terms = request.GET['search']

		#Get url version of search values
		#remove page from request.GET
		param_temporary = request.GET.copy()
		if 'page' in param_temporary:
			del param_temporary['page']
		search_url = urlencode(param_temporary).split("=")[-1]

		#Query for search and filter resulting value
		query = get_query(search_terms, ['name', 'description', 'item_number'])
		post_list = Product.objects.filter(check_sold, query) 


		#Get the pages
		num_of_pages = getPages(post_list.count(), MAX_POSTS_PER_PAGE)
		paging_info = generatePagingInfo(page_num_int, num_of_pages, 
			MAX_PAGES_TO_SHOW)

		#redirect to last page if page_num > num_of_pages
		if post_list and page_num_int > num_of_pages:
			redirect_url = "/%s", num_of_pages
			return HttpResponseRedirect('/category/0/?search=%s' % search_terms)

	else:

		if cat_id_int == 0:
			post_list = Product.objects.filter(check_sold)
		else:
			cat_object = get_object_or_404(Category, cat_id=cat_id)
			name = cat_object.name
			post_list = Product.objects.filter(check_sold, categories__pk=cat_id)

		#Get the pages
		num_of_pages = getPages(post_list.count(), MAX_POSTS_PER_PAGE)
		paging_info = generatePagingInfo(page_num_int, num_of_pages, 
			MAX_PAGES_TO_SHOW)

		#redirect to last page if page_num > num_of_pages
		if post_list and page_num_int > num_of_pages:
			redirect_url = "/%s", num_of_pages
			return HttpResponseRedirect('/category/%s' % cat_id)

	if post_list:
		post_info = getPostInPage(page_num_int, MAX_POSTS_PER_PAGE, post_list)

	#Package context
	context = {
	'current':'category',
	'title':name,
	'category': cat_id,
	'latest_post_list': post_info,
	'url_var': "webapp:category_view",
	'category_list':getCategories(), 
	'search_terms': search_url,
	}

	context.update(paging_info)


	return render(request, 'webapp/post_list.html', context)


def product(request, product_id):
	"""
	Post page of the web app

	Keyword arguments:
	cat_id -- the category if of the category
	post_id -- the id of the post
	"""
	#Get web post and check if post exists. If it does not 404
	product = get_object_or_404(Product, product_id=product_id)
	cat_id = 0;

	if 'cat' in request.GET and request.GET['cat'] != '':
		cat_id = int(request.GET['cat'])
		print cat_id


	if cat_id != 0:
		category = product.categories.get(cat_id=cat_id)
		if not category:
			raise Http404("Product in that category does not exist")
		else:
			category_name=category.name
	else:
		category_name='All Products'


	context = {
		'current':'product',
		'category_name':category_name,
		'cat_id':cat_id,
		'category_list':getCategories(),
		'product': product,
	}

	return render(request, 'webapp/product.html', context)


def getCategories():
	"""
	Helper function to obtain categories available
	"""
	category_list = getAllCategories() #Get All Categories
	category_index = range(len(category_list))
	category_combined = zip(category_list, category_index)

	return category_combined

class ProductSitemap(Sitemap):
    changefreq = "daily"
    priority = 0.5

    def items(self):
        return Product.objects.all()

myproject/webapp/templates/webapp/contact.html
{% load webapp_tags %}

<!-- Header -->
{% include "webapp/header.html" %}

<div class="container container-xtra-small container-text-alignment container-center">
<!-- Title -->
	<h3 class="page-title">{{ title }}</h3>
	<form action="{% url 'webapp:contact' %}" method="POST" class="post-form">
		{% csrf_token %}

		{{ form.non_field_errors }}
		<div class="col-md-12 col-lg-12 input-container">
			{{ form.item.errors }}
			{{ form.item }}
		</div>
		<div class="col-md-4 col-lg-4 input-container input-container-left">
			{{ form.name.errors }}
			{{ form.name }}
		</div>

		<div class="col-md-4 col-lg-4 input-container input-container-middle">
			{{ form.email.errors }}
			{{ form.email }}
		</div>

		<div class="col-md-4 col-lg-4 input-container input-container-right">
			{{ form.phone.errors }}
			{{ form.phone }}
		</div>

		<div class="col-md-12 col-lg-12 input-container">
			{{ form.message.errors }}
			{{ form.message }}
		</div>

		<div class="col-md-12 col-lg-12 input-container">
			{{ form.location.errors }}
			{{ form.location }}
		</div>

		<div class="required">* Required Fields</div>

        <button type="submit" class="btn btn-default">Send</button>
    </form>


</div>
<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/error.html
<!-- Header -->
{% include "webapp/header.html" %}

<!-- Title -->
<div class="container">
	<h3 class="page-title">{{ title }}</h3>
	<h4>Sorry, cannot process your request at this time. Please try again later.</h4>
</div>
	
<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/footer.html
{% load staticfiles %}

<!-- Footer Navigation -->
		<footer>
			<div class="col-lg-6 company-info">
				<p>
                    Sepro Mineral Systems Corporation Canada</br>
                    101A -9850 201 Street Langley, British Columbia V1M 4A3</br>
                    Office:&nbsp;+(1) 604-888-5568</br> 
                    N.A. Toll Free: +(1) 800-900-5568</br>
                    Fax:&nbsp;+(1) 604-888-5521
               	</p>

			</div>
			<div class="col-lg-6 social">
				<p>
                    <a href="https://www.facebook.com/pages/Sepro-Mineral-Systems/201074393248171" class='social-logo facebook'></a>
                    <a href="http://www.youtube.com/user/SeproMineralSystems" class='social-logo youtube'></a>
                    <a href="http://www.linkedin.com/company/1605152?trk=tyah&trkInfo=tas%3Asepro%20mineral" class='social-logo linkedin'></a>
               	</p>
			</div>

			<div class="col-lg-12 footer-disclaimer">
				<div class="col-sm-12 col-lg-6 push-lg-6">
					<p>Copyright 2017 - All rights reserved.</p>
				</div>
				<div class="col-sm-12 col-lg-6 pull-lg-6">
					<p>
						<a href="{% url 'webapp:terms'%}" class=''>Terms of Usage</a> |
						<a href="{% url 'webapp:policy'%}" class=''>Private Policy</a> |
						<a href="{% url 'webapp:disclaimer'%}" class=''>Disclaimer</a>
					</p>
				</div>
			</div >
		</footer>
<!-- Closing Footer -->
	</body>
	

</html>

myproject/webapp/templates/webapp/generic.html
{% load staticfiles %}

<!-- Header -->
{% include "webapp/header.html" %}


<div class="container container-xtra-small container-text-alignment container-center">

	{{ content | safe}}

</div>

<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/header.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
	<head>
    	<meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta name="google-site-verification" content="2NKjIo3OqlCMBQ7bOxnG-YWZRfG4BamUKTzHGAkfLuE" />
    	<title>MiningDeals</title>
      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{% static 'webapp/css/master.css' %}" />
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
      <script type="text/javascript" src="{% static 'webapp/javascript/webapp.js' %}"></script>

    
  	</head>
        <!-- Add Script Here -->
    <!-- Latest compiled and minified JavaScript -->
      
  	<body>

      <header>

        <nav class="navbar navbar-fixed-top">
            <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#CollapseNavbar">
              &#9776;
            </button>
            <img class="home-logo-small hidden-sm-up "src="{% static 'webapp/image/Logo.png' %}" alt="Home"></a>
            <div class="collapse navbar-toggleable-xs" id="CollapseNavbar">
              <ul class="nav navbar-nav">

                {% if current == 'home'%}
                <li class="nav-item nav-home-text nav-item-link .nav-md active">
                  <a class="nav-link" href="/">Home</a>
                </li>
                {% else %}
                <li class="nav-item nav-home-text nav-item-link .nav-md">
                  <a class="nav-link" href="/">Home</a>
                </li>
                {% endif %}

                {% if current == 'category' or current == 'product' %}
                <li class="nav-item nav-item-link nav-lg .nav-md active">
                  <a class="nav-link" href="{% url 'webapp:category' %}">Products</a>
                </li>
                {% else %}
                <li class="nav-item nav-item-link nav-lg .nav-md">
                  <a class="nav-link" href="{% url 'webapp:category' %}">Products</a>
                </li>
                {% endif %}

                <li class="nav-item nav-home-logo nav-lg">
                  <a class="nav-link" href="/">
                    <img class="home-logo"src="{% static 'webapp/image/Logo.png' %}" alt="Home"></a>
                </li>

                {% if current == 'contact' %}
                <li class="nav-item nav-item-link nav-lg .nav-md active">
                  <a class="nav-link" href="{% url 'webapp:contact' %}">Contact Us</a>
                </li>
                {% else %}
                <li class="nav-item nav-item-link nav-lg .nav-md">
                  <a class="nav-link" href="{% url 'webapp:contact' %}">Contact Us</a>
                </li>
                {% endif %}

              </ul>
            </div>
          </nav>

          
      </header>


      

      
  		
  		

myproject/webapp/templates/webapp/index.html
{% load staticfiles %}

<!-- Header -->
{% include "webapp/header.html" %}

<!-- Title -->
<div class="banner">
	<h1 class="banner-title">“Your most reliable source for quality surplus and used equipment.”</h1>
</div>

<div class="container index-description container-text-alignment container-xtra-small container-center">

	<h2> About Us </h3>
	<p>&nbsp;</p>

	{{ home_description.home_description | safe }}

	<a href="{% url 'webapp:category' %}" class="btn btn-primary">SEE OUR INVENTORY</a>
</div>

<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/paging.html
{% load webapp_tags %}


<!--  List Paging  -->
{% if latest_post_list %}
<div class="pagination-container">
	<nav aria-label="Page navigation">
		  <ul class="pagination">
		  		{% if current_page != 1 %}
			    <li class="page-item">
				      <a class="page-link" href="?page={{ firstpage }}&search={{ search_terms }}" aria-label="First">
					        <span aria-hidden="true">&laquo;</span>
					        <span class="sr-only">First Page</span>
				      </a>
			    </li>
			    <li class="page-item">
				      <a class="page-link" href="?page={{ previous_page }}&search={{ search_terms }}" aria-label="Previous">
					        <span aria-hidden="true">&lsaquo;</span>
					        <span class="sr-only">Previous Page</span>
				      </a>
			    </li>
			    {% endif %}

			    	<!--  Page Numbers  -->	
				{% for page_number in pages %}
					{% if current_page == page_number %}
						<li class="page-item active">
					      	<a class="page-link" href="?page={{ current_page }}&search={{ search_terms }}">{{ current_page }}</a>
					    </li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{ page_number }}&search={{ search_terms }}">{{ page_number }}</a></li>
					{% endif %}
				{% endfor %}

					<!--  Next Page and Last Page  -->	
				{% if current_page != last_page %}
					<li class="page-item">
				      <a class="page-link" href="?page={{ next_page }}&search={{ search_terms }}" aria-label="Next">
					        <span aria-hidden="true">&rsaquo;</span>
					        <span class="sr-only">Next Page</span>
				      </a>
			    	</li>
					<li class="page-item">
				      <a class="page-link" href="?page={{ last_page }}&search={{ search_terms }}" aria-label="Next">
					        <span aria-hidden="true">&raquo;</span>
					        <span class="sr-only">Last Page</span>
				      </a>
			    	</li>
				{% endif %}
		  </ul>
	</nav>
</div>
{% endif %}
	<!--  End Paging -->

myproject/webapp/templates/webapp/post_list.html
<!-- Header -->
{% include "webapp/header.html" %}

<!--  Post List  -->
<div class="container">
			<div class='col-md-3 col-lg-2 sidebar-div'> 
				{% include "webapp/sidebar.html" %}
			</div>

			<!-- List Posts-->
			<div class='col-md-9 col-lg-10 content-div'> 
				{% include "webapp/post_listing.html" %}

				{% include "webapp/paging.html" %}
			</div>
			<!--  Add Paging System -->
</div>
<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/post_listing.html
{% load webapp_tags %}
	<div class="row">
		<h3 class="page-title">{{ title }}</h3>
		{% if latest_post_list %}
			{% for post in latest_post_list %}
			  	<div class="card">
					{% with post.picture_set.all|first as picture %}
					<div class="img-container">
						<img src="{{ picture.picture.url }}">
					</div>
					{% endwith %}
					<div class="card-block">
				    	<h4 class="card-title card-back"><a href="{% url 'webapp:product' post.product_id %}?cat={{ category }}">{{ post.name }}</a></h4>
				    </div>
				    <div class="card-block card-img-overlay">
			  			<h4 class="card-title"><a href="{% url 'webapp:product' post.product_id %}?cat={{ category }}">{{ post.name }}</a></h4>
					  	<h6 class="card-subtitle">Price: {{ post.price }}</h6>
					  	<h6 class="card-subtitle">Quantity: {{ post.quantity }}</h6>
					    <p class="card-text">{{ post.description|safe|truncatewords:100 }}</p>
					</div>
			 	</div>
			{% endfor %}
		{% else %}
		    <p>No posts are available.</p>
		{% endif %}

	</div>

myproject/webapp/templates/webapp/product.html
{% load webapp_tags %}

<!-- Header -->
{% include "webapp/header.html" %}
<div class="container">
<!-- Title -->
	<div class='col-md-3 col-lg-2 sidebar-div'> 
	{% include "webapp/sidebar.html" %}
	</div>
	<div class='col-md-9 col-lg-10 content-div container-text-alignment container-center'> 
		
		<ul class="post-information">
			<!-- Breadcrumbs -->
			<div class="breadcrumbs">
				<a href="{% url 'webapp:category_view' cat_id %}">{{ category_name }}</a> >> <a href="{% url 'webapp:product' product.product_id %}?cat={{ cat_id }}">{{ product.name }}</a>
			</div>
			<!-- Carousel -->
			<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="false">
				<ol class="carousel-indicators">

					{% for picture in product.picture_set.all %}
						{% if forloop.counter0 == 0 %}
							<li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
						{% else %}
							<li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}"></li>
						{% endif %}
					{% endfor %}
				</ol>
				<div class="carousel-inner" role="listbox">

					{% for picture in product.picture_set.all %}
						{% if forloop.counter == 1 %}
							<div class="carousel-item active">
						  		<img class="carousel-img img-responsive center-block" src="{{ picture.picture.url }}" alt="Slide {{ forloop.counter }}">
							</div>
						{% else %}
							<div class="carousel-item">
						  		<img class="carousel-img img-responsive center-block" src="{{ picture.picture.url }}" alt="Slide {{ forloop.counter }}">
							</div>
						{% endif %}
					{% endfor %}

				</div>
				<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
					<span class="carousel-button icon-prev " aria-hidden="true"></span>
					<span class="sr-only">Previous</span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
					<span class="carousel-button icon-next" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>

			<!-- Post Information -->
			<h3 class="post-title">{{ product.name }}</h3>
			<li>Product ID: {{ product.item_number }}
			<li>Category:{% for category in product.categories.all %} <a href="{% url 'webapp:category_view' category.cat_id %}">{{ category.name }}</a>{% endfor %}</li>
			<li>Price: {{ product.price }}</li>
			<li>Quantity: {{ product.quantity }}</li>
		</ul>
		
		<p>
			{{ product.description|safe|linebreaks }}
		</p>

		<a href="{% url 'webapp:contact' %}?item={{ product.name|replaceSpaceUnderscore }}" class="btn btn-primary">Inquire</a>
	</div>
</div>
<!--  Footer  -->
{% include "webapp/footer.html" %}

myproject/webapp/templates/webapp/sidebar.html
<!-- Add Sidebar of Categories -->
{% if category_list %}
	<ul class='sidebar'>
		<form method="get" action="{% url 'webapp:category_view' 0 %}">
			<label for="id_q">Search:</label>
        		<input type="text" name="search" id="id_q"/>
        		<input type="submit" value="Submit"/>
        </form>
        
		<li>
			<h5 id="category-list">Categories</h5>
		</li>
		<div id="sidebar-item-list">
		{% if category == "0" %}
		<li class="sidebar-item active">
			<a class="sidebar-link" href="{% url 'webapp:category'%}">All Products</a>
		</li>
		{% else %}
		<li class="sidebar-item">
			<a class="sidebar-link" href="{% url 'webapp:category'%}">All Products</a>
		</li>
		{% endif %}

  		{% for category, index in category_list %}

    		{% ifequal title category.name %}
			<li class="sidebar-item active">
    		<a class="sidebar-link" href="{% url 'webapp:category_view' category.cat_id %}">{{ category.name }}</a>
			</li>
    		{% else %}
			<li class="sidebar-item">
    		<a class="sidebar-link" href="{% url 'webapp:category_view' category.cat_id %}">{{ category.name }}</a>
			</li>
    		{% endifequal %}

  		{% endfor %}
  		</div>
	</ul>
{% else %}
    <p>No categories are available.</p>
{% endif %}

myproject/webapp/templates/webapp/thanks.html
<!-- Header -->
{% include "webapp/header.html" %}

<!-- Title -->
<div class="container">
	<h3 class="page-title">{{ title }}</h3>
	<h4>We have processed your request. Please be patient, we will contact you as soon as possible.</h4>
</div>

<!--  Footer  -->
{% include "webapp/footer.html" %}